### ISSUE TITLE
If there is no brand, Adding new item throwing unexcepted error.

### ISSUE THREAD

**Issue by SezginEge** [XomniCloud/xomni-cms-vnext#11]
![items addedit](https://cloud.githubusercontent.com/assets/6282991/6427586/e9cafedc-bf8d-11e4-8ae5-229ef0ae0f2b.PNG)

**Comment by daronyondem** [comment]
This is related to the previous generation of our CMS. Currently out of context for the nextGen repository. Moving this to our internal tracking tools. From now on as an internal member of the team please submit old generation CMS releated issues through our internal tooling.
