### ISSUE TITLE
Client Side Analytics, Stuck In "Loading" Screen and "Management" Option is not Visible

### ISSUE THREAD

**Issue by nseckinoral** [XomniCloud/xomni-cms-vnext#15]
Client side analytics page is getting stuck in loading screen and "Management" option is not visible in the uppermenu.

I'm using google chrome, latest version.

Error in the console: "Uncaught SyntaxError: Unexpected token G"

Steps to re-produce:

1.Select catalog from the upper menu
2.From the navigation menu, select Analytics/Client Side Analytics

Tenant: team-ist

**Comment by ilkayilknur** [comment]
This issue was resolved via dd105cdf6424690a0239d0cfb0d3bd99fbd7b547 and 00a29da7a062112f6f853bb548005d4d00110715 .
