### ISSUE TITLE
Integration endpoint page UI design needs to be reviewed

### ISSUE THREAD

**Issue by ilkayilknur** [XomniCloud/xomni-cms-vnext#18]

**Comment by daronyondem** [comment]
What branch should I use? dev or is it somewhere else like temp-css? Make sure you refer to a particular location in the source control repo to make things easier for people like me who randomly jumps into the project. Thanks.

**Comment by ilkayilknur** [comment]
@daronyondem you're right about giving particular location for  implementation in issues. :+1: 
This issue was about css implementation of the page from scratch. I think @SezginEge added css styles to the page in PR https://github.com/XomniCloud/xomni-cms-vnext/pull/34 When we accept this PR, we can close this issue.

@SezginEge please make sure that when sending PRs you mentioned previously opened related issues.

**Comment by SezginEge** [comment]
@ilkayilknur Okay.

**Comment by daronyondem** [comment]
Thanks for the clarification guys. Appreciated.

**Comment by gokhangulbiz** [comment]
Closed. #69
