### ISSUE TITLE
Modal popup does not work when you refresh the page.

### ISSUE THREAD

**Issue by SezginEge** [XomniCloud/xomni-cms-vnext#42]
It affects all pages. To repeat the issue:

- Open msg-integration page.
- Wait until modal close.
- Refresh page and modal popup does not work.

**Comment by ilkayilknur** [comment]
It looks like there is a module loading problem. I fixed this issue on my machine and I'm gonna send a PR this week.

**Comment by gokhangulbiz** [comment]
Fixed c991872.
