### ISSUE TITLE
Integration Endpoint Deletion Warning

### ISSUE THREAD

**Issue by daronyondem** [XomniCloud/xomni-cms-vnext#57]
We need to add the text below as an additional warning in a separated inline box into the current "Are you sure?" message dialog.

"Deleting your integration endpoint will delete all related configuration and disable all third party data access integration as well."

**Comment by SezginEge** [comment]
@daronyondem Sorry, but I couldn't understand what you mean by "inline box" ?

**Comment by daronyondem** [comment]
Here is an example of an inline warning box.

![photo_2015-05-29_13-04-20](https://cloud.githubusercontent.com/assets/2984187/7880542/46d5acd8-0603-11e5-8d42-e5f082335543.jpg)
