### ISSUE TITLE
When adding a new Device Type, Id should be optional.

### ISSUE THREAD

**Issue by nseckinoral** [XomniCloud/xomni-cms-vnext#83]
If you try to post a new Device Type using "Xomni.Management.Company.DeviceTypes.DeviceTypesClient" , Device Type Id is required. However, new Id will be generated on server side.

**Comment by ilkayilknur** [comment]
This issue needs to be in our typescript repository. https://github.com/XomniCloud/xomni-sdk-ts-preview

**Comment by nseckinoral** [comment]
Thanks for the heads up! Opened a new one: https://github.com/XomniCloud/xomni-sdk-ts-preview/issues/37
